"""Render Reflow markdown into Canvas-compatible HTML.

Canvas's wiki page editor accepts a subset of HTML. We intentionally do
*not* embed CSS or scripts — Canvas strips most of it anyway, and any
styling should match the host course's theme.

The accessibility wins from Reflow (semantic headings, alt text, real
lists, real tables) survive the conversion because the markdown is
already semantic. This function exists to render that markdown, rewrite
image URLs from Reflow S3 to absolute URLs Canvas can resolve, and
prepend a small banner explaining the page's origin.

Uses ``mistune`` (already a project dependency) for the markdown → HTML
step.
"""

from __future__ import annotations

import html as _html
import re
from dataclasses import dataclass

import mistune

BANNER_HTML = (
    '<p><em>This page is an accessible, reflowable version of the original PDF, '
    "generated by Equalify Reflow. If anything looks wrong, the original PDF "
    'is linked at the bottom of this page.</em></p>'
)


@dataclass
class RenderedPage:
    title: str
    html: str


def render(
    markdown: str,
    *,
    title: str,
    original_pdf_url: str | None = None,
    image_base_url: str | None = None,
) -> RenderedPage:
    """Convert Reflow markdown into a Canvas-ready HTML body.

    ``image_base_url`` is prepended to any relative image src found in the
    markdown — Reflow returns ``![alt](figures/foo.png)`` style references
    and Canvas needs absolute URLs.
    """

    body_md = markdown
    if image_base_url:
        body_md = _rewrite_image_paths(body_md, image_base_url.rstrip("/"))

    # mistune.html() returns a string; the renderer escapes HTML in the
    # markdown source by default, which is what we want for Canvas.
    # The str() coerces because mistune's type hint is a union (str | list)
    # even though the default renderer only ever returns str.
    html_core = str(mistune.html(body_md) or "")

    parts: list[str] = [BANNER_HTML, html_core]
    if original_pdf_url:
        parts.append(
            f'<hr><p><a href="{original_pdf_url}">Original PDF</a></p>'
        )

    return RenderedPage(title=title, html="\n".join(parts))


_RELATIVE_IMG_RE = re.compile(r"!\[([^\]]*)\]\((?!https?://|/)([^)]+)\)")


def _rewrite_image_paths(markdown: str, base_url: str) -> str:
    def repl(match: re.Match[str]) -> str:
        alt = match.group(1)
        path = match.group(2)
        return f"![{alt}]({base_url}/{path.lstrip('/')})"

    return _RELATIVE_IMG_RE.sub(repl, markdown)


def render_link_stub(
    *,
    title: str,
    accessible_url: str,
    original_pdf_url: str | None = None,
) -> str:
    """A small (<8KB) Canvas Page body that links out to the full accessible HTML.

    Canvas Cloud's edge WAF (CloudFront) rejects Page REST writes whose body
    exceeds ~8KB, which is almost every real document. So the full converted
    HTML is uploaded as a course file and the Page itself is just this stub
    pointing at it — guaranteed tiny, so the PUT clears the WAF at any document
    size. See the canvas-waf-page-body-limit note.
    """
    safe_title = _html.escape(title or "this document")
    parts = [
        "<p><em>This is the accessible, reflowable version of the original "
        "PDF, generated by Equalify Reflow.</em></p>",
        "<p><strong>"
        f'<a href="{_html.escape(accessible_url)}">Open the accessible '
        f"version of &ldquo;{safe_title}&rdquo;</a></strong></p>",
    ]
    if original_pdf_url:
        parts.append(
            f'<hr><p><a href="{_html.escape(original_pdf_url)}">Original PDF</a></p>'
        )
    return "\n".join(parts)
