"""Render Reflow markdown into Canvas-compatible HTML.

Canvas's wiki page editor accepts a subset of HTML. We intentionally do
*not* embed CSS or scripts — Canvas strips most of it anyway, and any
styling should match the host course's theme.

The accessibility wins from Reflow (semantic headings, alt text, real
lists, real tables) survive the conversion because the markdown is
already semantic. This function exists to render that markdown, rewrite
image URLs from Reflow S3 to absolute URLs Canvas can resolve, and
prepend a small banner explaining the page's origin.

Uses ``mistune`` (already a project dependency) for the markdown → HTML
step.
"""

from __future__ import annotations

import html as _html
import re
from dataclasses import dataclass

import mistune

BANNER_HTML = (
    '<p><em>This page is an accessible, reflowable version of the original PDF, '
    "generated by Equalify Reflow. If anything looks wrong, the original PDF "
    'is linked at the bottom of this page.</em></p>'
)


@dataclass
class RenderedPage:
    title: str
    html: str


def render(
    markdown: str,
    *,
    title: str,
    original_pdf_url: str | None = None,
    image_base_url: str | None = None,
) -> RenderedPage:
    """Convert Reflow markdown into a Canvas-ready HTML body.

    ``image_base_url`` is prepended to any relative image src found in the
    markdown — Reflow returns ``![alt](figures/foo.png)`` style references
    and Canvas needs absolute URLs.
    """

    body_md = markdown
    if image_base_url:
        body_md = _rewrite_image_paths(body_md, image_base_url.rstrip("/"))

    # mistune.html() returns a string; the renderer escapes HTML in the
    # markdown source by default, which is what we want for Canvas.
    # The str() coerces because mistune's type hint is a union (str | list)
    # even though the default renderer only ever returns str.
    html_core = str(mistune.html(body_md) or "")
    html_core = _promote_standalone_images_to_figures(html_core)
    html_core = _add_table_header_scopes(html_core)

    parts: list[str] = [BANNER_HTML, html_core]
    if original_pdf_url:
        parts.append(
            f'<hr><p><a href="{original_pdf_url}">Original PDF</a></p>'
        )

    # Applied last, after every other transform, so nothing re-escapes the
    # entities we introduce.
    return RenderedPage(
        title=title, html=_defuse_ip_literals("\n".join(parts))
    )


# A dotted quad: four 1-3 digit groups. Deliberately not validating the
# 0-255 range — the point is to match what a firewall's pattern matches,
# and those match the shape, not the semantics.
_DOTTED_QUAD_RE = re.compile(r"\b(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\b")


def _defuse_ip_literals(html_str: str) -> str:
    """Write IPv4 literals with entity-encoded dots.

    Course material legitimately links to tools hosted at bare IP
    addresses — the SPRITE structure-search server is one — and a raw
    dotted quad anywhere in a request body is a stock signature for
    SSRF and malicious-link rules in managed WAF rule sets. Canvas Cloud
    sits behind CloudFront, so a Page write containing one is rejected at
    the edge with an HTML 403 that Canvas never sees and that looks
    identical to a permissions failure.

    Measured against CSUEB's WAF on 2026-08-04 (course 50594): a raw
    literal was blocked in an ``href`` *and* in plain body text, over
    both http and https; the entity-encoded form passed. The rule matches
    the literal string and does not decode entities first.

    ``&#46;`` is decoded by browsers in attribute values and in text, so
    the rendered page is indistinguishable to a reader: links resolve,
    text reads the same, copy-paste still works. Nothing is lost but the
    byte pattern.

    This defuses the signature rather than removing the content — the
    honest fix is a WAF exception, but that is the institution's to grant
    and a document should not fail to publish while waiting for one.
    """
    return _DOTTED_QUAD_RE.sub(
        lambda m: f"{m.group(1)}&#46;{m.group(2)}&#46;{m.group(3)}&#46;{m.group(4)}",
        html_str,
    )


_THEAD_RE = re.compile(r"<thead\b[^>]*>(.*?)</thead>", re.IGNORECASE | re.DOTALL)
_TBODY_ROW_RE = re.compile(r"<tr\b[^>]*>(.*?)</tr>", re.IGNORECASE | re.DOTALL)
_BARE_TH_RE = re.compile(r"<th(?![^>]*\bscope=)([^>]*)>", re.IGNORECASE)


def _add_table_header_scopes(html_str: str) -> str:
    """Add ``scope`` to table header cells.

    A ``<th>`` without ``scope`` leaves a screen reader guessing which cells
    a header governs, which is exactly the association WCAG 2.2 SC 1.3.1
    (Info and Relationships) is about. Markdown table syntax has no way to
    express it, so mistune emits bare ``<th>`` and the semantic detail the
    correction agents worked out gets dropped on the floor at the last step.

    Rules applied:
      * ``<th>`` inside ``<thead>`` -> ``scope="col"``
      * a ``<th>`` leading a ``<tbody>`` row -> ``scope="row"``

    Existing ``scope`` attributes are never overwritten — if a future
    renderer starts emitting them, this becomes a no-op rather than a
    fight.
    """

    def _mark(match: re.Match[str], value: str) -> str:
        inner = _BARE_TH_RE.sub(
            lambda m: f'<th scope="{value}"{m.group(1)}>', match.group(1)
        )
        return match.group(0).replace(match.group(1), inner, 1)

    # Column headers.
    html_str = _THEAD_RE.sub(lambda m: _mark(m, "col"), html_str)

    # Row headers: a <th> that opens a row outside <thead>.
    heads = {m.group(1) for m in _THEAD_RE.finditer(html_str)}

    def _row(match: re.Match[str]) -> str:
        if any(match.group(0) in h for h in heads):
            return match.group(0)  # already handled as a column header
        return _mark(match, "row")

    return _TBODY_ROW_RE.sub(_row, html_str)


_RELATIVE_IMG_RE = re.compile(r"!\[([^\]]*)\]\((?!https?://|/)([^)]+)\)")


# Matches a paragraph whose only content is a single ``<img>`` — that's
# what CommonMark emits for a markdown line that's "just an image"
# (``![alt](src)`` on its own line). Whitespace around the img is
# allowed. Inline images (image + surrounding text inside the same
# ``<p>``) intentionally do NOT match.
_STANDALONE_IMG_PARAGRAPH_RE = re.compile(
    r"<p>\s*(<img\b[^>]*?/?>)\s*</p>",
    re.IGNORECASE,
)


def _promote_standalone_images_to_figures(html: str) -> str:
    """Rewrap a paragraph that's only an image as ``<figure><img></figure>``.

    Why: CommonMark wraps any block-level "just an image" line in a
    ``<p>``. WeasyPrint then maps the ``<img>`` to a PDF/UA ``Figure``
    structure element nested INSIDE a ``P`` — which is wrong for
    accessibility. Per PDF/UA-1, a standalone figure should sit at
    the same level as paragraphs (``Figure`` as sibling of ``P``,
    not its child). Acrobat's accessibility checker flags the nested
    form, and screen readers can mis-announce reading order.

    Inline images (image embedded in flowing prose) are left alone —
    they SHOULD be ``Figure`` inside ``P`` per PDF/UA.
    """
    return _STANDALONE_IMG_PARAGRAPH_RE.sub(r"<figure>\1</figure>", html)


def _rewrite_image_paths(markdown: str, base_url: str) -> str:
    def repl(match: re.Match[str]) -> str:
        alt = match.group(1)
        path = match.group(2)
        return f"![{alt}]({base_url}/{path.lstrip('/')})"

    return _RELATIVE_IMG_RE.sub(repl, markdown)


def render_link_stub(
    *,
    title: str,
    accessible_url: str,
    original_pdf_url: str | None = None,
) -> str:
    """A small (<8KB) Canvas Page body that links out to the full accessible HTML.

    Canvas Cloud's edge WAF (CloudFront) rejects Page REST writes whose body
    exceeds ~8KB, which is almost every real document. So the full converted
    HTML is uploaded as a course file and the Page itself is just this stub
    pointing at it — guaranteed tiny, so the PUT clears the WAF at any document
    size. See the canvas-waf-page-body-limit note.
    """
    safe_title = _html.escape(title or "this document")
    parts = [
        "<p><em>This is the accessible, reflowable version of the original "
        "PDF, generated by Equalify Reflow.</em></p>",
        "<p><strong>"
        f'<a href="{_html.escape(accessible_url)}">Open the accessible '
        f"version of &ldquo;{safe_title}&rdquo;</a></strong></p>",
    ]
    if original_pdf_url:
        parts.append(
            f'<hr><p><a href="{_html.escape(original_pdf_url)}">Original PDF</a></p>'
        )
    return "\n".join(parts)
